# Service: Pod'larınıza network erişimi sağlar
# Load balancer görevi görür ve trafiği sağlıklı Pod'lara dağıtır
apiVersion: v1
kind: Service
metadata:
  name: spring-vet-service
  namespace: spring-vet-app
  labels:
    app: spring-vet
spec:
  # Hangi Pod'lara trafik gönderileceğini belirler
  selector:
    app: spring-vet
  
  # Port yapılandırması
  ports:
  - name: http
    port: 80          # Service'in dinlediği port
    targetPort: 8080  # Container'ın dinlediği port
    protocol: TCP
  
  # Service tipi - LoadBalancer yerel ortamda Minikube tarafından yönetilir
  type: LoadBalancer